### ISSUE TITLE
Likely incorrect card elevation in 1.11

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2038]
This issue is about the elevation of the main screen cards in `release/1.11.x` after #1912.

* [x] None of the other issue templates apply to this issue.

See https://github.com/corona-warn-app/cwa-app-android/pull/1912#pullrequestreview-555954874.

> I think I introduced an inconsistency with the intended elevation […], as I spotted some code that explicitly set the risk card to `10dp` (e.g. `TracingDisabledBox`). […] Maybe you could try to find out what the intended elevation is, and make sure to set it correctly.

The current behaviour, to my knowledge, is that all cards in the main screen of `release/1.11.x` have a very strong `10dp` elevation. I suggest you check again what the correct elevation would be, as I see reason to assume it should actually be `4dp` for most of the cards.

--- 
Internal Tracking ID: [EXPOSUREAPP-4519](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4519)

**Comment by dsarkar** [comment]
@fynngodau Thanks. Devs are informed.

Best wishes, 
DS 
  
--- 
Corona-Warn-App Open Source Team 
Internal Tracking ID: [EXPOSUREAPP-4519](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4519)

**Comment by MikeMcC399** [comment]
"Fixed card elevation (EXPOSUREAPP-4519)" https://github.com/corona-warn-app/cwa-app-android/pull/2075 is included in [v1.11.0-RC2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC2).

**Comment by fynngodau** [comment]
I'm repeating what I said in #2075 here so it doesn't get lost in a closed PR:

The PR is probably only a partial fix to what I explained here – see for example this code in `TracingDisabledBox`:

    override val viewBinding = lazy {
        TracingContentDisabledViewBinding.inflate(
            layoutInflater,
            itemView.findViewById(R.id.box_container),
            true
        ).also {
            it.root.elevation = resources.getDimension(R.dimen.elevation_strong)
        }
    }

This code does not work, IIRC because it sets the wrong attribute (`app:cardElevation` vs. `android:elevation`).

The existence of this code implies to me that *certain* cards *should* have `elevation_strong`, which was the reason I created this issue – either this and similar setters need to be fixed, or this code needs to be removed.

**Comment by dsarkar** [comment]
@fynngodau Forwarded info into JIRA ticket.

**Comment by MikeMcC399** [comment]
@fynngodau 

Has this issue been properly addressed in the 1.11.0 release now or are there outstanding issues to be tracked?

**Comment by fynngodau** [comment]
@MikeMcC399 The code I mentioned is [still there](https://github.com/corona-warn-app/cwa-app-android/blob/a204c6ada1d05ba26ca54c341e69f4ff416f2ca8/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/risk/TracingDisabledBox.kt#L23), and to my knowledge it still does not work.

**Comment by heinezen** [comment]
@fynngodau Thanks. We have notified the devs about this.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Looking at the [code](https://github.com/corona-warn-app/cwa-app-android/blob/ac0016331c14598e5102d2a405f6740f7fd57514/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/tracing/ui/details/items/risk/TracingDisabledBox.kt#L23) in the `release/2.0.x` branch this hasn't been fixed yet, or @fynngodau?

**Comment by fynngodau** [comment]
I confused `TracingDisabledBox`, which appears on the Risk Details screen, with `TracingDisabledCard`, which appears on the home screen. Everything is in fact working correctly. Sorry for the inconvenience.
