### ISSUE TITLE
Contact Journal: Keyboard not visible when adding multiple entries in a Row

### ISSUE THREAD

**Issue by Paul-Lukas** [corona-warn-app/cwa-app-android#2658]
## Avoid duplicates
* [ x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ x ] Bug is not already reported in another issue

## Technical details

- Device name: Motorola one Vision / Motorola one Macro
- Android version: 10
- App version: 1.14.3

## Describe the bug

When adding multiple entries in a row the keyboard for the name field won't show up automatically in every entry after the first one, but the cursor will. Because of the name field being selected, as shown by the blinking cursor. 
Also, you can't just tap on the name field, you have to first select a different field.

## Steps to reproduce the issue

1. Open CWA and tap Journal
2. If using Journal for first time, then tap "OPEN JOURNAL"
3. Tap date today, tap + PERSON
4. Note how the Keyboard shows up
5. Type "Test" for example
6. Tap Save
7. Tap + PERSON
8. Note how the Keyboard won't show up but the Cursor in the Name field blinks.
9. Try tapping the Name field and notice how it won't change anything

## Expected behaviour

The keyboard just showing up, similar to the first time

---
Internal Tracking ID: [EXPOSUREAPP-5914](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5914)
Internal Tracking ID: [EXPOSUREAPP-5869](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5869) related issue.

**Comment by DerVogel2020** [comment]
I discovered a similar bug in 1.14.3 when editing existing persons or locations but wanted to wait for 1.15 and first check whether it has been already fixed before reporting it.

**Comment by MikeMcC399** [comment]
@Paul-Lukas 
I can't reproduce this on Samsung Galaxy or on Google Pixel so I'm guessing it is device specific.

**Comment by heinezen** [comment]
@DerVogel2020 Can you tell us what device you are using?

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Hey @Paul-Lukas ,

Thanks for the hint. We have created a ticket for this issue in our internal Jira system. The development team will take a look at your issue.

----
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
@heinezen I use a Samsung Galaxy A5 2017

**Comment by heinezen** [comment]
@DerVogel2020 Thank you, I've updated the ticket with the device info.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@DerVogel2020 
> I use a Samsung Galaxy A5 2017

I also have a Samsung Galaxy A5 (2017) SM-A520F and I am using the Samsung Keyboard on this device. The phone is running Android 8.0.0 with Build number R16NW.A520FXXUGCTKA. 

I can't reproduce this issue. Could you post a screenshot showing the issue on your device please?

Here is my screen shot after executing Step 7 from the repro steps (i.e. tapping + PERSON for the second time). The cursor is in the "First name, last name" field and it is blinking (not captured in the screenshot) and the keyboard is displayed and useable.

![Add Person EN](https://user-images.githubusercontent.com/66998419/111909764-dfba0080-8a5e-11eb-9f12-a69c9f8b7523.jpg)

**Comment by DerVogel2020** [comment]
OK, couldn't repoduce this one as well, but as mentioned a similar one:
- Tap "Tagebuch"
- Tap "Personen bearbeiten"
- Tap an already existing person
- Cursor is blinking in the "Vorname, Nachname"-Field, but keyboard in the "Vorname, Nachname"-Field only shows after klicking "Telefon" or "E-Mail" and then the "Vorname, Nachname"-Field
The same when editing Locations:
- Tap "Tagebuch"
- Tap "Orte bearbeiten"
- Tap an already existing location
- Cursor is blinking in the "Bezeichnung"-Field, but keyboard in the "Bezeichnung"-Field only shows after klicking "Telefon" or "E-Mail" and then the "Bezeichnung"-Field

Should I open a new Ticket for this? As mentioned, I wanted to wait for 1.15 and first check whether it has been already fixed before reporting it.

**Comment by Paul-Lukas** [comment]
@MikeMcC399

![Screenshot_20210321-174520.png](https://user-images.githubusercontent.com/68750116/111913218-6b3a8e00-8a6d-11eb-89e2-9fafaeb512c3.png)

I have tried SwiftKey and Gboard. Both show the same behavior.

Also both my devices show the same bug. Both Motorola, like I wrote earlier.
The Motorola one vision is an android one device. The one Macro not, don't know if that makes a difference.

**Comment by Paul-Lukas** [comment]
@DerVogel2020 
What you describe is basically the same problem, but with editing existing Places/Persons. 
I am able to reproduce what you describe. Like the Original Problem the first time everything works after the first try I encounter the problem too.

Most likely there is a Problem with the App or Android Handling the Form.

**Comment by MikeMcC399** [comment]
@DerVogel2020 / @Paul-Lukas 

The problems which the repro steps in the original report https://github.com/corona-warn-app/cwa-app-android/issues/2658#issue-836899362 from @Paul-Lukas and from the description in https://github.com/corona-warn-app/cwa-app-android/issues/2658#issuecomment-803608447 from @DerVogel2020 look like they are related. In both cases the keyboard is not being displayed when it ought  to be.

For the issue of @Paul-Lukas (https://github.com/corona-warn-app/cwa-app-android/issues/2658#issuecomment-803608447) I found that the keyboard is not displaying reliably on CWA 1.14.3 when trying to edit a Person entry. In my tests sometimes it was shown, sometimes not. I don't know if we need a second issue. Perhaps we should wait for dev feedback first?

**Comment by MikeMcC399** [comment]
The issue
"Keyboard not displayed for Contact Journal / Edit People"
I can see happening also on 1.15.1-RC0. The first time I accessed an Edit People entry the keyboard was shown. When I cancelled the edit and repeated the action the keyboard was not shown. I'm not sure that is always the case. It just seems intermittent, but at least I can say that the issue still occurs on the build currently in development.

**Comment by dsarkar** [comment]
FYI 

Internal Tracking ID: [EXPOSUREAPP-5869](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5869) related issue:


**[Android] Contact Journal: On second edit, no keyboard**

**Steps:**
App is installed
Create a person in contact journal
Edit Name of that person
go back to "Edit People" screen
Try to edit name again of the same person
No keyboard appears on first attribute (Name)

**Workaround:**
Click on second or third attribute, then keyboard appears.
Click on first attribute (NAme), keyboard is now available.

**Expected result:**
Keyboard should appear when clicking on any text field

**Actual Result:**
Keyboard does not appear when clicking on first text field (attribute NAME), when I try to edit the name of the same person a second time.

**Comment by MikeMcC399** [comment]
@dsarkar 
For Internal Tracking ID: [EXPOSUREAPP-5869](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5869) related issue:

[Android] Contact Journal: On second edit, no keyboard

I get mixed results!

On Pixel 3a emulator, Android 11 with CWA 1.14.3 (or with CWA 1.15.1-RC0 from current release/1.15.x branch): 

1. The first time editing a Person, the keyboard appears. Do no editing, no save, tap on X next to Person, tap again on same entry of Person and **no** keyboard appears.
2. If you now add a new Person and go back to Edit Person then the keyboard appears again.

That is similar to what you described.

Now on a Samsung Galaxy A5 (2017) with Android 8.0.0 and CWA 1.14.3 **I don't even get the keyboard on the first use of Edit Person.**

Your workaround (tap Phone field, then return to Name field) works in both configurations.

**Comment by MikeMcC399** [comment]
Internal Tracking ID: [EXPOSUREAPP-5869](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5869) is a regression from version 1.13.2. 

1.14.3 changed the Person record from Name only to Name, Phone and E-Mail. In 1.13.2 where only the Name is shown, the keyboard always appears.

**Comment by ralfgehrer** [comment]
The isuse should be fixed by this PR: https://github.com/corona-warn-app/cwa-app-android/pull/2674

**Comment by DerVogel2020** [comment]
> The issue should be fixed by this PR: https://github.com/corona-warn-app/cwa-app-android/pull/2674

Thanks. Is there already a release date for 2.0?

**Comment by heinezen** [comment]
@DerVogel2020 There's no concrete date that we can give out yet, but 2.0 will be the next regular release after 1.15.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Version 2.0 has been released and should have reached all users by now. Can you confirm the fix @DerVogel2020?

**Comment by DerVogel2020** [comment]
It's fixed.
@Paul-Lukas I think you can close this issue.

**Comment by Paul-Lukas** [comment]
@DerVogel2020
Everything is fixed and works like expected.

I will close the issue.

**Comment by dsarkar** [comment]
@Paul-Lukas @DerVogel2020 Thanks for contributing here. Best wishes, DS 

---
Corona-Warn-App Open Source Team
