### ISSUE TITLE
Ursache: 9002 Parameter specified as non-null is null (in contact journal)

### ISSUE THREAD

**Issue by gleusch** [corona-warn-app/cwa-app-android#2992]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: LG Velvet LM-G900EM
- Android version: 11 V20b-EEA-XX 1. Februar 2021, 4.19.113, RKQ1.201105.002
- App version: 2.0.4 18211213000

## Describe the bug

When entering notes to a "Kontakttagebuch" entry, and then de-selecting the entry again without leaving the notes entry field first an error popup "URSACHE 9002: Etwas ist schiefgelaufen / Parameter specified as non-null is null ..." appears (see screen shots.

## Steps to reproduce the issue

1. Go to "Tagebuch" (Diary). 
2. Select a day
3. Check one "Person" or "Ort" (person/place) -- bug is reproducible with both
4. Enter something into the "Notiz (z.B. geringer Abstand)" (Notes) entry field, but do not leave the field (i.e. do not remove the focus of the field)
5. Uncheck the check box on the top left of said person or place to remove the entry from this day's diary
6. Error message appears

![photo_2021-04-28_15-33-09](https://user-images.githubusercontent.com/11923141/116412656-31606280-a837-11eb-91c6-56c32a99813b.jpg)
![photo_2021-04-28_15-33-21](https://user-images.githubusercontent.com/11923141/116412661-31f8f900-a837-11eb-9480-b58881eb8b54.jpg)

## Expected behaviour

Either the entry just gets deselected, deleting the notes, or a confirmation dialog on whether the user wants to deselect the entry losing the notes first. 

----
Internal Tracking-ID: [EXPOSUREAPP-6992](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6992)

**Comment by DerVogel2020** [comment]
Same on Samsung A5 (2017). Similar problem was fixed in #2703, when deselecting a person/location without entering a note. So point 4 is important.

**Comment by gleusch** [comment]
> Same on Samsung A5 (2017). Similar problem was fixed in #2703, when deselecting a person/location without entering a note. So point 4 is important.

Okay, #2703 indeed sounds very similar -- I missed that one when checking whether this bug had already been reported. Thank you for noting! Feel free to merge the two issues then (dupe + reopen)

**Comment by DerVogel2020** [comment]
I would not merge them, because the the one (without entering a note) is already fixed in Version 2.0.4.

**Comment by Jo-Achim** [comment]
Same here with: 
Android 10 with Android security update: April 1st, 2021
Nokia 7.1, Build: 00WW_4_15C_SP11
CWA version: 2.0.5
ENF: 18211515000
NetGuard Pro 2.295
Norton 360, v.5.7.0.5665

**Comment by heinezen** [comment]
@gleusch @Jo-Achim Thank you for reporting the issue.

We have informed the dev team and created an internal ticket for the issue: [EXPOSUREAPP-6992](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6992). The developers will take a look at this.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
This issue is still present in CWA 2.5.1 and I can't see any fix in a future release yet.

**Comment by DerVogel2020** [comment]
Any new on this? 
2.13.2:

Ursache:
java.lang.NullPointerException: Parameter specified as non-null is null: method de.rki.coronawarnapp.contactdiary.storage.entity.ContactDiaryPersonEncounterWrapperKt.toContactDiaryPersonEncounter, parameter <this>
	at de.rki.coronawarnapp.contactdiary.storage.entity.ContactDiaryPersonEncounterWrapperKt.toContactDiaryPersonEncounter(Unknown Source:2)
	at de.rki.coronawarnapp.contactdiary.storage.repo.DefaultContactDiaryRepository$updatePersonEncounter$2.invokeSuspend(DefaultContactDiaryRepository.kt:8)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks. Forwarded to the internal ticket.

**Comment by Ein-Tim** [comment]
@dsarkar 

What's the status of the internal ticket of this issue? Low Prio? This is something which really affects the UX and is important for the user. Still this issue remains unfixed for more than 7 months.

**Comment by Ein-Tim** [comment]
I think #4593 is the fix for this?

**Comment by MikeMcC399** [comment]
@gleusch / @Ein-Tim / @DerVogel2020 / @Jo-Achim 

I can't reproduce this issue any more using CWA 2.19.2.

Have any of you tested it recently? Can you still see the problem occurring with the latest CWA version?

**Comment by DerVogel2020** [comment]
It seems to be fixed in 2.19.1.
I can't reproduce this.

**Comment by Jo-Achim** [comment]
Hi @MikeMcC399,
The bug seems to be fixed (CWA 2.19.2 | Android 12).

**Comment by MikeMcC399** [comment]
@DerVogel2020 & @Jo-Achim 

Many thanks for cross-checking!

The issue should be closed in that case.
