### ISSUE TITLE
2.10.0-RC0 version numbering mismatch

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4044]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- App version: 2.10.0 RC0 / RC2

## Describe the bug

Release Candidate [v2.10.0-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.10.0-RC0) builds as 2.10.0-RC2.

## Steps to reproduce the issue

1. Checkout [v2.10.0-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.10.0-RC0)
2. In Android Studio: Build > Clean Project
3. Examine build log

```
> Configure project :Corona-Warn-App
Current VERSION_MAJOR: 2
Current VERSION_MINOR: 10
Current VERSION_PATCH: 0
Current VERSION_BUILD: 2
Used versionCode: 2100002
Used versionName: 2.10.0
AGPBI: {"kind":"warning","text":"API 'BaseVariant.getApplicationIdTextResource' is obsolete and has been replaced with 'VariantProperties.applicationId'.\nIt will be removed in version 7.0 of the Android Gradle plugin.\nFor more information, see TBD.\nTo determine what is calling BaseVariant.getApplicationIdTextResource, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.","sources":[{}]}
deviceForTesters adjusted versionName: 2.10.0-RC2

```
## Expected behaviour

The release numbering in https://github.com/corona-warn-app/cwa-app-android/releases should match the contents of https://github.com/corona-warn-app/cwa-app-android/blob/release/2.10.x/gradle.properties, particularly the setting for
`VERSION_BUILD=`

## Possible Fix

Re-release the build as RC2 or change gradle.properties to RC0

**Comment by mtwalli** [comment]
it can be closed , it is already fixed

**Comment by MikeMcC399** [comment]
@mtwalli 

PR #4045 fixes the issue that builds after commit https://github.com/corona-warn-app/cwa-app-android/commit/57edcda5b1b1deecde913624d33ba68a52af8575 with tag https://github.com/corona-warn-app/cwa-app-android/tree/v2.10.0-RC0 are now labelled RC1.

It doesn't fix the issue that the build from tag https://github.com/corona-warn-app/cwa-app-android/tree/v2.10.0-RC0 is still labelled RC2 as described here in the original issue.

If you think that it is not important to correct the [v2.10.0-RC0 tag](https://github.com/corona-warn-app/cwa-app-android/tree/v2.10.0-RC0) then I will close the issue.

**Comment by mtwalli** [comment]
We can not change the number for the previous build. we have corrected it for the next build. it is a build for testers . the right build number for the release will be correct. please close it ?
