### ISSUE TITLE
Twitter Reports: Users are unable to register tests

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4410]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- Android version:  10
- App version: 2.13.3

## Describe the bug

Two twitter users are reporting that the "No internet connection" warning is shown during the process of registering a test result, although they are connected to the internet. 

## Steps to reproduce the issue

Not exactly clear, I can register a test in my app. 

## Expected behaviour

The app should not show the "No internet connection" warning during the process of registering a test result if an internet connection is available. 

## Additional context

Twitter Thread: https://twitter.com/JmVolckmann/status/1461303203337805827?s=20

---
Internal Tracking ID: [EXPOSUREAPP-10665](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10665)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-10665](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10665)

**Comment by dsarkar** [comment]
TSI is working on it.

**Comment by Ein-Tim** [comment]
@dsarkar Thanks!

**Comment by thomasaugsten** [comment]
The problem should be solved

**Comment by dsarkar** [comment]
@Ein-Tim See https://github.com/corona-warn-app/cwa-app-android/issues/4410#issuecomment-972894305. Maybe you can forward this info to the twitter user? Thanks for reporting!

**Comment by Ein-Tim** [comment]
@dsarkar @thomasaugsten 

Thanks! I forwarded this for confirmation to the Twitter thread. 
I will give you feedback here once I heard back from the Twitter users.

**Comment by Ein-Tim** [comment]
The Twitter user attempting to register a RAT is still encountering the same issue: https://twitter.com/lebennormal/status/1461341604862595077?s=21
He has restarted his phone before trying.

The Twitter user attempting to register a PCR test did not report back yet.

**Comment by Ein-Tim** [comment]
Feedback from the user attempting to register a PCR test: Same problem as before. 

cc @thomasaugsten

**Comment by dsarkar** [comment]
@Ein-Tim thanks for the feedback. will be forwarded.

**Comment by Ein-Tim** [comment]
Issue persists: https://twitter.com/MuppetPasta/status/1461613530101264384?s=20

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. forwarded to internal ticket.

**Comment by Ein-Tim** [comment]
The Twitter users meanwhile got their test result via other means or are not interested in registering their result in the CWA anymore. 

Thus I'm now closing this issue.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for relaying the info. Sorry to hear that it did not work for these users.
