### ISSUE TITLE
"Limit already reached" error after future date set then return to current date

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5183]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)

## Technical details

- Device name: Samsung Galaxy A52 5G (SM-A526B/DS)
- Android version: 12
- App version: 2.22.1
- Issue continues unresolved in version: 2.23.2

Note: The issue is not reproducible on Android 8.

## Describe the bug

App does not stop exposure check taking place when date incorrectly set to future before installation. After correcting the date the app risk tile first shows the error message ""Exposure check failed.". This changes after an hour to a green risk tile. After a further 5 hours have elapsed the error "Limit already reached" error message appears. This error message continues to show, even into following days, until the device's clock has progressed to reach the original future date.

## Steps to reproduce the issue

1. Set device date to two days into the future
2. Uninstall CWA (if already installed)
3. Install CWA
4. Open CWA
5. Tap "Let's Get Started"
6. Tap "Next"
7. Tap "Activate Exposure Logging"
8. Tap "Turn on"
9. Tap "Next", tap "Next"
10. Tap "Do Not Share"
11. Tap "OK"
12. Tap "Allow", disable optimized battery usage for Corona-Warn (device specific)
13. Dismiss QR Code Scanner pop-up by tapping on "X"
14. Note "Exposure check failed, with timestamp Today"<br>![Exposure check 1](https://user-images.githubusercontent.com/66998419/168478373-571760ea-705d-4f54-9078-6005a5c5d4e2.jpg)
15. Tap "Restart"
16. Note that this does not change the status
17. Leave CWA open and set the date correctly to today (or automatic)
18. Tap "Restart"
19. Note "Exposure check failed, with timestamp of previously set future day"<br>![Exposure check 2](https://user-images.githubusercontent.com/66998419/168478395-5835c122-f280-45ae-881a-9cdc84d3b7c4.jpg)
20. Close and re-open the app at hourly intervals. If "Exposure check failed." appears, then tap "Restart".
Two hours after initial installation, a green Low Risk tile is shown. (Alternatively just wait for 5 hours.)
21. On the 6th re-open an error message appears: "Limit already reached". 
22. (Android) Settings > Google > COVID-19 Exposure Notifications > three-dot symbol > Exposure checks shows 5 checks from the current day and one check from the future day. 

Open the app again the next day. The error message "Limit already reached" still appears.
![Limit already reached](https://user-images.githubusercontent.com/66998419/168533295-8b442378-c1d0-4f81-867c-d5621d41280d.jpg)

## Expected behavior

- The app should prevent an exposure check from taking place if the date does not match the server date.
- With the "Exposure check failed" status an error message should be shown that the reason for this failure was an incorrectly set time.
- Also, if an exposure check is allowed to happen, then the app should recover and start carrying out exposure checks when the date is corrected.
- If "Limit already reached" appears, then this condition should clear automatically after 24 hours.

## Additional information
- Recovery is possible by resetting the app
- To clear the wrong exposure check history in the Google log it is necessary to uninstall and re-install the app
- There is no FAQ article covering this situation. https://www.coronawarn.app/en/faq/results/#limit_reached says the device will recover after 24 hours
- [Google Exposure Notifications API modes documentation](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes) specifies `provideDiagnosisKeys` quota - Six per day (counter resets at 00:00 UTC)

---
Internal Tracking ID: [EXPOSUREAPP-9077](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9077)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for report: Internal Tracking ID: [EXPOSUREAPP-9077](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9077) Best, DS

**Comment by MikeMcC399** [comment]
According to https://www.coronawarn.app/en/faq/results/#limit_reached the "Limit already reached" message should clear after waiting 24 hours. This is however not the case in the situation where the device's clock has been set to a future date, then corrected back to the current date, followed by being left alone to advance to new correct dates as time naturally elapses.

Notably, in the Android Settings > Google > COVID-19 Exposure Notifications > three-dot menu > Exposure checks, as the date advances into future dates and continues to display "Limit already reached" errors, there are no new exposure checks logged. So it seems that exposure checks are being attempted, failing and not being logged. This may need attention from Google support. The first step however would be to get attention from the CWA Android development team.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your comment, forwarded.

**Comment by MikeMcC399** [comment]
From examining the error log:

CWA starts producing the 39508 error ([FAILED_RATE_LIMITED](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationStatusCodes#public-static-final-int-failed_rate_limited)) after the device's date has been corrected to the current date. If the device is connected to WAN, this will be after approximately 5 hours following the date correction.

```
2022-05-18T09:07:08.275Z D/SubmissionQuota: No new quota available (now=2022-05-18T09:07:08.274Z, availableAt=2022-05-21T00:00:00.000Z)
2022-05-18T09:07:08.276Z D/SubmissionQuota: Not enough quota: want=1, have=0
2022-05-18T09:07:08.277Z E/DefaultDiagnosisKeyProvider: No key files submitted because not enough quota available.
2022-05-18T09:07:08.284Z D/DefaultDiagnosisKeyProvider: Performing key submission.
2022-05-18T09:07:08.284Z I/DefaultENFVersion: Comparing current ENF client version 18221514000 with 17000000
2022-05-18T09:07:08.284Z I/DefaultDiagnosisKeyProvider: Provide diagnosis keys with DiagnosisKeyFileProvider
2022-05-18T09:07:08.298Z W/DefaultDiagnosisKeyProvider$provideDiagnosisKeys: Key submission failed because 39508: 
2022-05-18T09:07:08.301Z D/DownloadDiagnosisKeysTask: Initiate Rollback
2022-05-18T09:07:08.301Z E/DownloadDiagnosisKeysTask: de.rki.coronawarnapp.nearby.modules.diagnosiskeyprovider.QuotaExceededException: Quota limit exceeded.
```

---
CWA begins risk calculation again after the device clock has progressed until it has reached the day after the previously set future date in UTC terms i.e. 01:00 CET or 02:00 CEST of the following day.

```
2022-05-21T01:06:45.064Z D/SubmissionQuota: Consuming quota: old=6, new=5
2022-05-21T01:06:45.063Z I/SubmissionQuota: Quota reset: oldQuota=0, lastReset=2022-05-20T04:06:06.996Z -> newQuota=6, thisReset=2022-05-21T01:06:45.053Z
2022-05-21T01:06:45.074Z I/DefaultENFVersion: Comparing current ENF client version 18221514000 with 17000000
2022-05-21T01:06:45.075Z I/DefaultDiagnosisKeyProvider: Provide diagnosis keys with DiagnosisKeyFileProvider
2022-05-21T01:06:45.077Z D/DefaultDiagnosisKeyProvider: Performing key submission.
2022-05-21T01:06:46.118Z D/DownloadDiagnosisKeysTask: Diagnosis Keys provided (success=true)
2022-05-21T01:06:46.123Z I/DownloadDiagnosisKeysTask: Finished (isCanceled=false).
```

**Comment by MikeMcC399** [comment]
A suggestion to improve the error handling in the app would be to output a different message if the risk tile is showing that the last update is a date in the future. This can only happen if the device has undergone time travel which probably means that the Random IDs stored may contain corrupted time-stamps and should not be used any more.

The app should give better instructions in this situation and I currently think that the only clean recovery is to uninstall and re-install the app.

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> issue cant be reproduced with R 2.12. 

@MikeMcC399
Is the problem still happening with the latest version? Normally I would close this issue since the related Jira issue is already closed in November 2021.

I would need to create a fresh one with new information.

**Comment by MikeMcC399** [comment]
@svengabr 

> Developer comment:
>
>> issue cant be reproduced with R 2.12.
>
>Is the problem still happening with the latest version? Normally I would close this >issue since the related Jira issue is already closed in November 2021.
>
>I would need to create a fresh one with new information.

Release 2.12 was from October 2021 (see https://www.coronawarn.app/en/blog/2021-10-19-cwa-version-2-12).

I wrote the above repro steps based on Release 2.22.1 from April 2022 (https://www.coronawarn.app/en/blog/2022-04-19-cwa-2-21/) which is more recent compared to when the developers looked at the issue 8 months ago.

I don't think that there have been any changes made to the app between 2.22.1 and 2.23.2 in this area since I last tested, so I assume that the problem still exists.

Unfortunately checking this once again on the current version 2.23.2 would require significant effort due to the nature of the issue (see repro steps). I suggest to open a new Jira issue and for the developers to look at the available information. The extracts from the logs should be a good way to pin-point the root cause and find a fix.

If you have the developers engaged after looking at the existing information then I would be willing to repeat the tests.

**Comment by MikeMcC399** [comment]
@svengabr 
I have re-tested on the current CWA Android 2.23.2. As expected, the problem still occurs.

Yesterday the message "Limit already reached ... Please check your risk status again tomorrow" was output.
Today the same message appears. 

The assumption that waiting for a new day clears the error status is incorrect. 

The app needs to trap the condition where the last update appears to be a date in the future. It should probably advise instead to check the date setting of the device. If the device is currently set to the correct date, then the app needs to be uninstalled and reinstalled in order to clear Random IDs which have been stored with corrupt date stamps.

**Comment by svengabr** [comment]
@MikeMcC399 I have re-used the existing issue

**Comment by mtwalli** [comment]
@MikeMcC399  I'm trying to reproduce this issue ,but I'm experiencing different behaviour.

## Scenario 1
1- Set device time into the future.
2- Install CWA 
3- I saw:
|  Time warning message |  Exposure check has not been done | 
|---|---|
| <img width="569" alt="Screenshot 2022-08-16 at 18 39 07" src="https://user-images.githubusercontent.com/25054729/184938177-c16cdcdc-7e1d-464d-b11c-ccba74ddfe26.png"> |  <img width="569" alt="Screenshot 2022-08-16 at 18 39 26" src="https://user-images.githubusercontent.com/25054729/184938332-5aeb292a-9347-4e0b-b89b-eb9b086cb1ed.png"> |  

4- Correct device time , lets exposure check to run again 
<img width="569" alt="Screenshot 2022-08-16 at 18 52 53" src="https://user-images.githubusercontent.com/25054729/184938865-81b2b258-87d4-4c15-b830-ac8168e4beca.png">

## Scenario 2
1- Install CWA on device with right time
2- Travel to the future 
3- I see the time warning message and risk status failed 
<img width="569" alt="Screenshot 2022-08-16 at 18 55 10" src="https://user-images.githubusercontent.com/25054729/184939250-104c9c7b-8f57-446b-8624-aab3049905c8.png">

I tried this on two different devices one has the whitelisted gmail account 1_000_000 time quota per day and normal gmail account 6 times quota  per day, In both devices when time was correct only one check that been done according to Google settings 

are you still able to reproduce this issue ?

**Comment by MikeMcC399** [comment]
@mtwalli

This issue was reported for Samsung Galaxy A52 5G (SM-A526B/DS) with Android 12 and CWA Android 2.23.2.

Your screenshots show SM-G950F, which looks like Samsung Galaxy S8. Is that correct? Are you testing with a physical device? You didn't say which Android version or app version that you are testing with. Perhaps you were using Android 8?

I tried with Samsung Galaxy A5 (2017) SM-A520F with Android 8.0.0 and CWA Android 2.25.0 and I confirm that I see the same error message as you see "Exposure Check Not Possible" / "The time set on your device does not match the current time. As a result, your risk cannot be checked right now. Please set the correct time in your device settings."

The error message "Exposure Check Not Possible" / "The time set on your device does not match the current time. As a result, your risk cannot be checked right now. Please set the correct time in your device settings." does **not** appear on Android 11 or 12. Would you expect it to be shown on these Android versions?

Perhaps you could repeat your tests with Android 11 or 12?

**Comment by MikeMcC399** [comment]
@mtwalli 

- I have added a new issue https://github.com/corona-warn-app/cwa-app-android/issues/5463 for the missing error message on Android 12.

**Comment by mtwalli** [comment]
@MikeMcC399 
> Your screenshots show SM-G950F, which looks like Samsung Galaxy S8. Is that correct? Are you testing with a physical device? You didn't say which Android version or app version that you are testing with. Perhaps you were using Android 8?

Yes, it is a physical device Samsung S8 running Android 9, cwa v2.26.0.2 (not released yet )

> Perhaps you could repeat your tests with Android 11 or 12?
Yes it should.

I'm currently looking into it on Android 13 , I did not see the dialog either

**Comment by mtwalli** [comment]
@MikeMcC399  I opened a PR linked above to potentially fix these issues, can you verify if it resolves them?

**Comment by MikeMcC399** [comment]
@mtwalli 

> I opened a PR linked above to potentially fix these issues, can you verify if it resolves them?

Thank you for your efforts to resolve this issue!

If I build and run the branch [fix/9077-server-time-parsing](https://github.com/corona-warn-app/cwa-app-android/tree/fix/9077-server-time-parsing) using Android Studio I receive the error "Cause: 3 Something went wrong<br>Your Corona-Warn-App is correctly installed, but the "COVID-19 Exposure Notifications System" is not available on your smartphone's operating system" when I attempt to "Activate Exposure Logging", since the app is not signed and I do not have access to an allowlisted account.

If you could provide me with either:
- a signed app or
- an allowlisted account

then I would be happy to test.

**Comment by mtwalli** [comment]
@MikeMcC399  Thanks for the feedback, Unfortunately I can't share the whitelisted  account publicly. Probably I can provide a signed testing APK with the first RC of 2.27.0

**Comment by MikeMcC399** [comment]
When I originally logged this issue, I saved the log file and I found:

```
2022-05-18T04:07:02.070Z E/AppConfigServer: Failed to get server time.
2022-05-18T04:07:02.070Z V/AppConfigServer: Time offset was 0ms
2022-05-18T04:07:02.070Z W/AppConfigServer: Server returned max-age=0: no-cache, no-store, max-age=0
```

- So hopefully PR https://github.com/corona-warn-app/cwa-app-android/pull/5465 will fix `E/AppConfigServer: Failed to get server time`.

**Comment by MikeMcC399** [comment]
@mtwalli 

> Probably I can provide a signed testing APK with the first RC of 2.27.0

If you have this available I can test next week,

**Comment by mtwalli** [comment]
> @mtwalli 
> 
> 
> 
> > Probably I can provide a signed testing APK with the first RC of 2.27.0
> 
> 
> 
> If you have this available I can test next week,
> 
> 
> 
> 

can you please send me your email address to mohamed.metwalli@sap.com? I will send you the APK to verify the fix.

**Comment by MikeMcC399** [comment]
@mtwalli 

Thank you for sending the test APK of `Corona-Warn-App-2.27.0-RC0-deviceForTesters-release.apk`! The test was successful! 👍🏻 

On Android 12, with the date 2 days in the future, exposure logging is blocked. When the date is corrected to today's date, exposure logging is immediately successful.

The risk tile does say: "Installed -2 days ago" however this is logical and it is only a cosmetic issue which does not need to be addressed. The resolution would be to uninstall the app and reinstall it with the date set correctly.

Since I have been able to test successfully on an official build, even though it is not a final release build, I will close the issue now.
