### ISSUE TITLE
No reset of counter for risk contacts after two weeks

### ISSUE THREAD

**Issue by ehambuch** [corona-warn-app/cwa-app-android#911]
My app shows "Low risk" (green) with "2 risks contacts" for more than two weeks now!

I would expect that the "risk contacts" would decrease to 0 after a certain period (2 weeks?).

Timeline:
Possible event with crowd of people - 26th Jun (?)
2 risk contacts diplayed in app - since 4th July
No update since then (phone has been restarted)

Regards

---
Internal Tracking ID: EXPOSUREAPP-1837

**Comment by SebastianWolf-SAP** [comment]
Probably related to https://github.com/corona-warn-app/cwa-backlog/issues/23, but we need to check if this is also already addressed or not. Until we have certainly, we will keep this issue open. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ehambuch** [comment]
![coronaapp](https://user-images.githubusercontent.com/9589050/88271218-22acb400-ccd7-11ea-8cbf-e63cd112c351.png)

Screenshot angefügt.

**Comment by akuckartz** [comment]
I had 3 "Risiko-Begegnungen" on July 12. Between then and now that number dropped to 2 and 1 later. But it now is still at 1.

**Comment by k5e** [comment]
On 2nd of July, I received a contact warning. It stays until today, 1st of August. I checked the keys and there is one "positive" hash that is logged repeatedly until 16th of July. After that no further records with number of hits >0 are there. The app insists on the assertion "1 Risiko-Begegnung".

**Comment by ehambuch** [comment]
Peeking into the source code, I assume that the ExposureSummary is never cleared (see ExposureSummaryDao). That could be a reason why the counter is not resetted.

**Comment by daimpi** [comment]
Someone on Twitter asked me to post their experience: they have the same problem with a "Risk-Contact but green" status persisting for 14 days now: https://twitter.com/Hckeck/status/1289833171828084737

Their system:
Android 6.0.1
CWA 1.1.1
"Prioritized Background" activated

This might indeed be an Android exclusive problem, as almost simultaneously someone under iOS [was reporting](https://twitter.com/twybn/status/1289866295748571137) that their number of risk encounters was reset to 0.

**Comment by akuckartz** [comment]
My number of "Riskobegegungen" Yesterday has increased from 1 to 2. Due to this bug I distrust the number.

**Comment by AFA-start** [comment]
Have the same issue: After 16 days there are still "2 Risikobegegnungen" in green > low risk. 
I use an Pixel 3a with Android 10
Regards
Arne

**Comment by pwoessner** [comment]
Hi all,

we addressed this issue in this commit here:
https://github.com/corona-warn-app/cwa-app-android/commit/90e9a6ae800af9b2438a56d8805ddb2ef2e41d99

Indeed, there was an issue with using the persisted ExposureSummary instead of the ExposureSummary directly from ENF.
It is currently planned to ship this fix with 1.3.

Thanks,
Philipp

**Comment by AFA-start** [comment]
Hi Philipp, 
thank you for letting us know. 
Is there a roadmap/timetable for the release date of version 1.3?

Regards
Arne

**Comment by pwoessner** [comment]
HI @AFA-start 
sorry I made a mistake. This will be already be included in Version 1.2 where we build the final release candidate last week. Unfortunately I cannot give an exact date when this version will be available.
Thanks,
Philipp

**Comment by pwoessner** [comment]
@AFA-start 
sorry for the complete confusion. I asked another colleague and this was unfortunately not part of v1.2.0 yet.
But it is indeed part of the v1.3.0 RC1 release:
https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.0-SNAPSHOT-RC1

But for this version (1.3.0) I also do not have an ETA but since we already build the RC and testing has started we hope we can publish this release asap.

Thanks,
Philipp

**Comment by AFA-start** [comment]
Hi @pwoessner,
thanks again. The big questions now is: Does the app still work or do it stuck in an old data set? In other words: Will new encounters be recognized?
Thank you so much for yor time!!!
I realy appricate this!
Arne

**Comment by pwoessner** [comment]
Hi @AFA-start 
no the app is never stuck in an old data set. The behaviour is like this:

- CWA downloads the infected keys
- The ENF will check if there are exposures
- If there was a match/exposure, the app will persist the exposure summary (details about the exposue)
- the risk calculation will use the last persisted exposure summary and will display these values to the user

At the moment this exposure summary will then be used if there is no new match from the Google ENF. But if there is a new exposure the old exposure summary will no longer be used and the new one will be displayed to the user.

Regards,
Philipp

**Comment by wilhelmrichter** [comment]
"1 Risikobegegnung.." wurde nie geloescht. 
Gerät: Samsung G990F ; Kernel 3.4.0  (2016-05-31) ; Android 6.0.1
So wird das nichts mit der Akzeptanz in der Bevölkerung. 
Erfahrene Projektentwickler hätten es übrigens wissen müssen. SAP hat noch nie was Ordentliches auf die Beine gestellt. Wer erinnert sich nicht an das total zum Stillstand gebrachte VW-Werk in Kassel, weil die SAP-Leichtmatrosen selbst einfachste Module nicht hinbekommen haben? Dies nur als highlight, ganz zu schweigen von dem auf den Leim gegangenen Mittelstand. Beispiele sind aus den 1990er Jahren. Nicht das die SAP-Hausjuristen mir noch ob der aktuellen Fälle am Zeug flicken...
Vielleicht hätte man 'mal bei den Leutchen von IBM anfragen sollen, oder Oracle oder, oder.
Die App ist mit diesem Anfängerfehler (sieht doch wirklich verdammt nach einem Indexfehler aus)  jedenfalls etwas für die Tonne.

**Comment by vaubaehn** [comment]
Guten Abend @wilhelmrichter ,
vermutlich würden sich alle freuen, wenn Sie sich konstruktiv einbringen. So könnten Sie beispielsweise den Indexfehler im Programmcode identifizieren und korrigieren, und einen der Community Manager darum bitten, Ihren korrigierten Code überprüfen und in die Anwendung übernehmen zu lassen.
Anschuldigungen helfen uns hier leider nicht weiter.
Vielen Dank für Ihre Unterstützung,
V. (ein normaler Nutzer)

**Comment by svengabr** [comment]
As @pwoessner already mentioned a while ago this issue is fixed with the upcoming release 1.3.0.

The RC1 is already available:
https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.0-SNAPSHOT-RC1

I will come back to close this issue once the update went live.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by GisoSchroederSAP** [comment]
> "1 Risikobegegnung.." wurde nie geloescht.
> Gerät: Samsung G990F ; Kernel 3.4.0 (2016-05-31) ; Android 6.0.1
> So wird das nichts mit der Akzeptanz in der Bevölkerung.
> Erfahrene Projektentwickler hätten es übrigens wissen müssen. SAP hat noch nie was Ordentliches auf die Beine gestellt. Wer erinnert sich nicht an das total zum Stillstand gebrachte VW-Werk in Kassel, weil die SAP-Leichtmatrosen selbst einfachste Module nicht hinbekommen haben? Dies nur als highlight, ganz zu schweigen von dem auf den Leim gegangenen Mittelstand. Beispiele sind aus den 1990er Jahren. Nicht das die SAP-Hausjuristen mir noch ob der aktuellen Fälle am Zeug flicken...
> Vielleicht hätte man 'mal bei den Leutchen von IBM anfragen sollen, oder Oracle oder, oder.
> Die App ist mit diesem Anfängerfehler (sieht doch wirklich verdammt nach einem Indexfehler aus) jedenfalls etwas für die Tonne.

Guten Abend @wilhelmrichter ;
Ich möchte mich den Tenor der anderen Leser und User anschließen und verweise vorsorglich auf den Code of Conduct [https://github.com/corona-warn-app/cwa-documentation/blob/master/CODE_OF_CONDUCT.md](url). 

Ihre persönliche Bewertung anderer Aktivitäten der SAP vor vielen Jahren ist für die Entwicklung der Corona Warn App weder hilfreich noch respektvoll. Eine solche Meinungsäußerung in diesem Repository lehnen wir ab. 

Daher bitte ich Sie, sich hier künftig sachlich und ziel-orientiert im Sinne der Community zu äußern. 
Vorab vielen Dank dafür.

**Comment by ehambuch** [comment]
Bug is fixed. The counter is now back to zero.

**Comment by akuckartz** [comment]
Finally this is fixed. But I think that this took far to long.

**Comment by mtb77** [comment]
@ehambuch can we close the issue then?

Thanks,

Sascha

Corona-Warn-App Open Source Team

**Comment by wilhelmrichter** [comment]
same as me. for further details i ´d like to point to my original post.

Wilhelm Richter

 
 

Gesendet: Sonntag, 06. September 2020 um 07:56 Uhr
Von: "Andreas Kuckartz" <notifications@github.com>
An: "corona-warn-app/cwa-app-android" <cwa-app-android@noreply.github.com>
Cc: "wilhelmrichter" <wilhelm_richter@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] No reset of counter for risk contacts after two weeks (#911)


 

Finally this is fixed. But I think that this took far to long.

**Comment by mgerlach** [comment]
I got the update to 1.3.0 recently. For me the counter has not been reset. It's been 1 for weeks now and is still showing one low risk encounter.
Phone: SM-G930F, Android 8.0.0, Basisband G930FXXS8ETC4, Build R16NW.G930FXXS8ETC6, Kernel 3.18.91-14843133-QB29774695 (Mar 10, 2020)

**Comment by daimpi** [comment]
@mgerlach on which date did the encounter first show up for you? Would you maybe share your ENF log? 🙂

**Comment by mgerlach** [comment]
Must have been around July 18. Where can I find the log?

**Comment by daimpi** [comment]
> Where can I find the log?

On your phone's main screen: settings -> Google -> COVID-19 exposure notifications
click on the field where it says "checks performed in the last 14 days", this will bring you to a long list. You can export his list by clicking on the burger menu in the top right corner of the screen and select export. 
To share the file here on GH, either rename the .json file to a .txt file or put it in a .zip archive.

**Comment by mgerlach** [comment]
Thanks. Here it is: https://drive.google.com/file/d/1u5qfIBPvx0f1yQ8OfEa8E04rWu4c0i_b/view?usp=drivesdk

**Comment by daimpi** [comment]
Thanks 🙂 
I just scanned your ENF log with https://felixlen.github.io/ena_log/ and got the following output:
![grafik](https://user-images.githubusercontent.com/22129968/92524884-2367be00-f223-11ea-826f-9f957fe372df.png)

This would indicate that you should have seen this match for the first time around Sept 5th. Does this sound plausible to you?

**Comment by mgerlach** [comment]
Yes, it does. So I got the app update a few days ago and it probably fixed the issue with the encounter in July, but there must have been an actual low risk encounter 4 days ago, too. I'll keep an eye on this. Thanks for checking!

**Comment by daimpi** [comment]
Ok nice 👍

Keep us posted how it goes with the new encounter 🙂.
